/*
 * Copyright 2016 Red Hat Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package io.vertx.mqtt.it;

import io.netty.handler.codec.mqtt.MqttVersion;
import io.vertx.core.Vertx;
import io.vertx.mqtt.MqttClient;
import io.vertx.ext.unit.junit.VertxUnitRunner;
import io.vertx.mqtt.MqttClientOptions;
import org.junit.After;
import org.junit.Before;
import org.junit.runner.RunWith;
import org.testcontainers.containers.GenericContainer;

/**
 * Base class for MQTT 5.0 integration tests running against a real Mosquitto 2.x broker.
 * The broker is started via Testcontainers using the same {@code mosquitto.conf} used by
 * the existing integration tests ({@code allow_anonymous true}, port 1883, WebSocket port 9001).
 * {@code -Dit.broker=hivemq} runs them against HiveMQ CE instead, see {@link MqttBrokerContainers}.
 */
@RunWith(VertxUnitRunner.class)
public abstract class Mqtt5ClientBaseIT {

  public GenericContainer<?> mosquitto = MqttBrokerContainers.create("eclipse-mosquitto:2.1.2-alpine", useWebSocket());

  protected int port;
  protected String host;

  @Before
  public void setUp() {
    mosquitto.start();
    port = mosquitto.getMappedPort(useWebSocket() ? MqttBrokerContainers.webSocketPort() : 1883);
    host = mosquitto.getHost();
  }

  @After
  public void stopBroker() {
    // runs after the tearDown of the subclass, a container left running would live until the end of the test JVM
    mosquitto.stop();
  }

  protected MqttClientOptions v5Options() {
    MqttClientOptions opts = new MqttClientOptions();
    opts.setVersion(MqttVersion.MQTT_5.protocolLevel());
    opts.setAutoGeneratedClientId(true);
    return opts;
  }

  /**
   * @return {@code true} when the client connects to the broker using MQTT over WebSocket instead of plain TCP
   */
  protected boolean useWebSocket() {
    return false;
  }

  protected MqttClient createClient(Vertx vertx) {
    return createClient(vertx, new MqttClientOptions());
  }

  protected MqttClient createClient(Vertx vertx, MqttClientOptions options) {
    return MqttClient.create(vertx, options.setUseWebSocket(useWebSocket()));
  }
}
